<?php

namespace AvesnesMedical\ecommerceBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProduitController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AvesnesMedical\ecommerceBundle\Controller\ProduitController();
        return $instance;
    }
}
