<?php

namespace AvesnesMedical\ecommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function getPhotoAvecProduit($id_produit)
    {
        $qb = $this->createQueryBuilder('ph');
        // On fait une jointure avec l'entité Categorie, avec pour alias « c »
        $qb ->join('ph.produit', 'pr')
            ->where($qb->expr()->in('ph.id', $id_produit)); // Puis on filtre sur le nom des catégories à l'aide d'un IN

        // Enfin, on retourne le résultat
        return $qb->getQuery()
            ->getResult();
    }
}
